export type CurrencyCode = 'XOF' | 'EUR' | 'USD';

export type StockStatus = 'NORMAL' | 'LOW' | 'OUT_OF_STOCK';

export type ItemCondition = 'Neuf' | 'Bon état' | 'À réparer' | 'Défectueux' | 'Hors service';

export type CategoryName = 
  | 'Équipement Informatique'
  | 'Matériel Roulant & Transport'
  | 'Mobilier de Bureau'
  | 'Matériel Événementiel & Audiovisuel'
  | 'Consommables & Fournitures'
  | 'Secours & Kit Médical'
  | 'Outillage & Maintenance'
  | 'Autres Équipements';

export interface InventoryItem {
  id: string;
  code: string; // e.g., SKU LOG-2026-001
  name: string;
  category: CategoryName;
  description: string;
  quantity: number;
  minThreshold: number; // Low stock alert level
  unitPrice: number; // FCFA or EUR
  totalValue: number; // quantity * unitPrice
  location: string; // e.g., Entrepôt Principal, Bureau Central, Antenne Ouest
  condition: ItemCondition;
  supplierName: string;
  lastRestockDate: string;
  barcode: string;
  imageUrl?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export type MovementType = 'IN' | 'OUT' | 'TRANSFER' | 'ADJUSTMENT';

export interface StockMovement {
  id: string;
  itemId: string;
  itemCode: string;
  itemName: string;
  type: MovementType;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  sourceLocation?: string;
  targetLocation?: string;
  reason: string; // Achats, Don, Distribution, Vente, Casse/Perte, Transfert Inter-Dépôt, Régularisation
  referenceDoc?: string; // N° BL, Facture, Bon de Livraison
  handlerName: string; // Responsable / Agent
  timestamp: string;
  notes?: string;
}

export type TransactionType = 'INCOME' | 'EXPENSE';

export type FinancialCategory = 
  | 'Achat Matériel & Équipement'
  | 'Achat Consommables'
  | 'Maintenance & Réparations'
  | 'Transport & Logistique'
  | 'Subventions & Dons'
  | 'Cotisations Membres'
  | 'Prestations & Événements'
  | 'Frais Administratifs'
  | 'Divers';

export type PaymentMethod = 'Virement Bancaire' | 'Chèque' | 'Espèces' | 'Mobile Money' | 'Carte Bancaire';

export type PaymentStatus = 'PAYE' | 'EN_ATTENTE' | 'ANNULE';

export type AccountName = 'Compte Bancaire AMM' | 'Caisse Principale Siège' | 'Mobile Money AMM';

export interface FinancialTransaction {
  id: string;
  type: TransactionType;
  category: FinancialCategory;
  title: string;
  description?: string;
  amount: number;
  date: string;
  paymentMethod: PaymentMethod;
  account: AccountName;
  status: PaymentStatus;
  receiptRef?: string;
  linkedMovementId?: string; // If transaction was generated by stock purchase
  createdByName: string;
  timestamp: string;
}

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
  categorySpecialty: CategoryName;
  taxId?: string;
  rating?: number; // 1-5 stars
  notes?: string;
}

export interface AssociationProfile {
  name: string;
  acronym: string;
  subtitle: string;
  address: string;
  phone: string;
  email: string;
  taxNumber: string;
  defaultCurrency: CurrencyCode;
  warehouseLocations: string[];
}

export interface BudgetLimit {
  category: FinancialCategory;
  allocatedAmount: number;
}

// Security & Authentication Module Types
export type UserRole = 'ADMIN' | 'LOGISTICS_MANAGER' | 'FINANCIAL_OFFICER' | 'AUDITOR' | 'AGENT';

export type UserStatus = 'ACTIVE' | 'SUSPENDED' | 'PENDING';

export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  role: UserRole;
  department: string;
  phone?: string;
  status: UserStatus;
  mfaEnabled: boolean;
  lastLogin: string;
  createdAt: string;
  avatarUrl?: string;
  permissions: string[];
}

export type AuditEventType = 
  | 'LOGIN' 
  | 'LOGOUT' 
  | 'FAILED_LOGIN' 
  | 'ROLE_CHANGE' 
  | 'STATUS_CHANGE' 
  | 'SESSION_TIMEOUT' 
  | 'PASSWORD_RESET' 
  | 'MFA_TOGGLE' 
  | 'PROFILE_UPDATE' 
  | 'ITEM_DELETE' 
  | 'DATABASE_RESET';

export interface AuditLogEntry {
  id: string;
  timestamp: string;
  userId: string;
  userEmail: string;
  userName: string;
  userRole: UserRole;
  action: AuditEventType;
  details: string;
  ipAddress?: string;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
}
